### ISSUE TITLE
Answer key doesn't match outcome from lab

### ISSUE THREAD

**Issue by AnnikaNoren** [learn-co-curriculum/dsc-statistical-power-lab#1]
In the second part of the lab (Sample size requirements for a given effect size), when I ran the code: 
p = power_analysis.solve_power(effect_size=.17, alpha=0.05, power=.8)
my answer was: 544.1357761564401.
The answer key has the same code: power.solve_power(effect_size=.17, alpha=0.05, power=.8)
and the answer is: 273.51381725963785

Then, the lab gives these variables: 
##### minimum sample size to start the simulations 
sample_size = 12
current = 0
n_sim = 10000

But the answer key is:
# minimum sample size to start the simulations 
sample_size = 12
null_rejected = 0
n_sim = 10000

My code fails because the variable current was used instead of null_rejected.

**Comment by bpurdy-ds** [comment]
This appears to have been corrected. Closed with commit: https://github.com/learn-co-curriculum/dsc-statistical-power-lab/issues/1#issue-500462775
