### ISSUE TITLE
Power

### ISSUE THREAD

**Issue by zshoorbajee** [learn-co-curriculum/dsc-statistical-power-lab#4]
## Link to Canvas

https://learning.flatironschool.com/courses/4957/assignments/166956?module_item_id=360614

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

### Source

```
Power = 1 - P (Type II error) = probability of finding an effect that is there
```

### Concern

Power is 1 - β, not 1 - P

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [x] IllumiDesk

**Comment by bpurdy-ds** [comment]
What is there is correct, but I agree it can be interpreted as Power = 1 - P and then in parenthesis Type II error. But the way it is supposed to be read is as Power = 1 - Probability(Type II error). I'll make this clearer.

**Comment by bpurdy-ds** [comment]
Commit is done as stated above: https://github.com/learn-co-curriculum/dsc-statistical-power-lab/issues/4#issue-1140497845
