### ISSUE TITLE
Statistical Power Lab

### ISSUE THREAD

**Issue by anonymous2020andbeyond** [learn-co-curriculum/dsc-statistical-power-lab#5]
## Link to Canvas

https://learning.flatironschool.com/courses/6222/assignments/226479?module_item_id=529268

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [X ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

### Concern

In this lab we are asked to create two simulations, but never are we told what those simulations are to accomplish overall.  Its great that the steps are provided to help us layout code, but without context, this lab seems much harder than it really is.

## (Optional) Proposed Solution

Before each of the simulations, add a description of what it is intended to do and what you should wind up with in terms of variables at the end.

## What OS Are You Using?

- [ ] OS X
- [ X] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
While we have kept the Statistical Power lesson for v3.0 of the curriculum, we have removed the lab. As such, we are no longer supporting this repo. Thank you for the suggestion, though.
